// <auto-generated />
namespace SocialNetwork_Img_Resizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SEED_Network_Image_Spec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SEED_Network_Image_Spec));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171223484_SEED_Network_Image_Spec"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
