// <auto-generated />
namespace SocialNetwork_Img_Resizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Network_Image_Spec_ProfileName_ADD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Network_Image_Spec_ProfileName_ADD));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171217206_Network_Image_Spec_ProfileName_ADD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
