// <auto-generated />
namespace SocialNetwork_Img_Resizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Table_Operations_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_Operations_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202004282206334_Table_Operations_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
